# Generated by Django 4.2.22 on 2025-06-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_device_alter_issue_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
