# Generated by Django 4.2.22 on 2025-06-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_issue_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='resolved_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
